apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  # As senhas devem ser codificadas em Base64.
  # Exemplo: echo -n 'app_password' | base64 -> YXBwX3Bhc3N3b3Jk
  # Exemplo: echo -n 'root_password' | base64 -> cm9vdF9wYXNzd29yZA==
  MYSQL_PASSWORD: "YXBwX3Bhc3N3b3Jk"
  MYSQL_ROOT_PASSWORD: "cm9vdF9wYXNzd29yZA=="