# --- Aplicação de Usuários ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-usuarios-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-usuarios
  template:
    metadata:
      labels:
        app: app-usuarios
    spec:
      # ----> INÍCIO DA ALTERAÇÃO <----
      securityContext:
        fsGroup: 33
        runAsUser: 33
        runAsGroup: 33
      # ----> FIM DA ALTERAÇÃO <----
      containers:
      - name: app-usuarios
        image: app-usuarios:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "db-usuarios-service"
        - name: DB_NAME
          value: "usuarios_db"
        - name: DB_USER
          value: "app_user"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: MYSQL_PASSWORD
        - name: ESTOQUE_API_URL
          value: "http://app-estoque-service:8082"
        - name: VENDAS_API_URL
          value: "http://app-vendas-service:8083"
        - name: APP_BASE_URL
          value: "http://localhost:8081" # Substitua pelo seu IP
        volumeMounts:
        - name: uploads-storage
          mountPath: /var/www/html/uploads
      volumes:
      - name: uploads-storage
        persistentVolumeClaim:
          claimName: pvc-uploads
---
apiVersion: v1
kind: Service
metadata:
  name: app-usuarios-service
spec:
  selector:
    app: app-usuarios
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80
---
# --- Aplicação de Estoque ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-estoque-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-estoque
  template:
    metadata:
      labels:
        app: app-estoque
    spec:
      # ----> INÍCIO DA ALTERAÇÃO <----
      securityContext:
        fsGroup: 33
        runAsUser: 33
        runAsGroup: 33
      # ----> FIM DA ALTERAÇÃO <----
      containers:
      - name: app-estoque
        image: app-estoque:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "db-estoque-service"
        - name: DB_NAME
          value: "estoque_db"
        - name: DB_USER
          value: "app_user"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: app-estoque-service
spec:
  selector:
    app: app-estoque
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 80
---
# --- Aplicação de Vendas ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-vendas-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-vendas
  template:
    metadata:
      labels:
        app: app-vendas
    spec:
      # ----> INÍCIO DA ALTERAÇÃO <----
      securityContext:
        fsGroup: 33
        runAsUser: 33
        runAsGroup: 33
      # ----> FIM DA ALTERAÇÃO <----
      containers:
      - name: app-vendas
        image: app-vendas:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "db-vendas-service"
        - name: DB_NAME
          value: "vendas_db"
        - name: DB_USER
          value: "app_user"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: MYSQL_PASSWORD
        - name: ESTOQUE_API_URL
          value: "http://app-estoque-service:8082"
---
apiVersion: v1
kind: Service
metadata:
  name: app-vendas-service
spec:
  selector:
    app: app-vendas
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 80